/*
Question #1: 
If we exclude the discounts that have been given, the expected profit margin for each product 
is calculated by: (retail price - cost) / retail price. 

Create a column that flags products with a name that includes “Vintage” as products from 
Nike Vintage and Nike Official otherwise. 

Calculate the expected profit margins for each product name and include the group that 
splits products between Nike Official and Nike Vintage in the result.
*/

/*
column products where name like 'Vintage'
column products where name like 'Officila*
profit margin = (retail price - cost) / retail price by products
*/


SELECT
    CASE
    	WHEN product_name LIKE('%Vintage%') THEN 'Vintage'
      WHEN product_name NOT LIKE('%Official%') THEN 'Official'
    END AS product_group,
		product_name,
    (retail_price - cost) / retail_price AS pr_margin	
FROM products

/*
Question #2: 
What is the profit margin for each distribution center? Are there any centers that stand out?
*/



/*
Question #3: 
The real profit margin per order item is calculated by: (sales price - cost) / sales price. 
By summing up all the order items, we will find the real profit margin generated by the products.

Calculate the profit margin for the Nike Official products: Nike Pro Tights, Nike Dri-FIT Shorts, and Nike Legend Tee
*/

/*
Question #4: 
Calculate the real profit margin by product and split the data using the created date before 2021-05-01 
and post 2021-05-01 for Nike Official order items.
*/

/*
Question #5: 
Calculate the profit margin by product for both Nike Official and Nike Vintage products in a single view
*/

/*
Question #6: 
What are the top 10 products by profit margin from Nike Official and Nike Vintage? Include the product name, profit margin, and what business unit (Nike Official or Nike Vintage) sells the product.
*/