/*
Question #1: 
If we exclude the discounts that have been given, the expected profit margin for each product 
is calculated by: (retail price - cost) / retail price. 

Create a column that flags products with a name that includes “Vintage” as products from 
Nike Vintage and Nike Official otherwise. 

Calculate the expected profit margins for each product name and include the group that 
splits products between Nike Official and Nike Vintage in the result.
*/

/*
column products where name like 'Vintage'
column products where name like 'Officila*
profit margin = (retail price - cost) / retail price by products
*/


SELECT
    CASE
    	WHEN product_name LIKE('%Vintage%') THEN 'Vintage'
      WHEN product_name NOT LIKE('%Official%') THEN 'Official'
    END AS product_group,
		product_name,
    (retail_price - cost) / retail_price AS pr_margin	
FROM products

/*
Question #2: 
What is the profit margin for each distribution center? Are there any centers that stand out?

profit margin = products (retail_price - cost) / reital_price
profit margin per COUNT distribution_center_id
*/ 

SELECT
		dc.name,
		(pr.retail_price - pr.cost) / pr.retail_price AS profit_margin
FROM products AS pr
JOIN distribution_centers AS dc
ON pr.distribution_center_id = dc.distribution_center_id


/*
Question #3: 
The real profit margin per order item is calculated by: (sales price - cost) / sales price. 
By summing up all the order items, we will find the real profit margin generated by the products.

Calculate the profit margin for the Nike Official products: Nike Pro Tights, Nike Dri-FIT Shorts, and Nike Legend Tee


SUM products Nike Official WHERE name = Pro Tights, Dri-FIT, Legend Tee

*/

SELECT
		'Nike Official' AS nike_official,
		product_name,
    SUM(retail_price - cost) / SUM(retail_price) AS sum_profit_margin
FROM products
WHERE 
		product_name LIKE('%Pro Tights%') 
    OR product_name LIKE('%Dri-FIT%') 
    OR product_name LIKE('%Legend Tee%')
GROUP BY nike_official, product_name


/*
Question #4: 
Calculate the real profit margin by product and split the data using the created date before 2021-05-01 
and post 2021-05-01 for Nike Official order items.
*/    


SELECT
		pr.product_name,
    CASE
    		WHEN oi.created_at < '2021-05-01' THEN 'Pre-May'
        ELSE 'Post-May'
    END AS may21_split,
    (SUM(pr.retail_price) - SUM(pr.cost)) / SUM(pr.retail_price) AS profit_margin
FROM products AS pr
JOIN order_items AS oi
ON oi.product_id = pr.product_id
GROUP BY 
		pr.product_name,
    CASE
    		WHEN oi.created_at < '2021-05-01' THEN 'Pre-May'
        ELSE 'Post-May'
    END
ORDER BY pr.product_name, may21_split;

/*
Research ChatGPT regarding task 4:

The profit margin should be calculated based on the total revenue and total costs of a specific segment 
(e.g., a product or a time period), rather than averaging the margins of individual order items. Calculating 
the margin at the individual order-item level and then deriving an average can lead to distortions, 
particularly when some order items have varying sales prices or costs. Methodologically, it is more accurate 
to aggregate all relevant costs and revenues first and then calculate the margin based on these totals.
*/

/*
Question #5: 
Calculate the profit margin by product for both Nike Official and Nike Vintage products in a single view
*/

SELECT 
		pr.product_name AS "Nike Official",
    (SUM(retail_price) - SUM(cost)) / SUM(retail_price) AS profit_margin
FROM products AS pr
WHERE product_name NOT LIKE('%Vintage%')
GROUP BY pr.product_name
UNION
SELECT 
		pr.product_name AS "Nike Vintage",
    (SUM(retail_price) - SUM(cost)) / SUM(retail_price) AS profit_margin
FROM products AS pr
WHERE product_name LIKE('%Vintage%')
GROUP BY pr.product_name
ORDER BY profit_margin
        
        

/*
Question #6: 
What are the top 10 products by profit margin from Nike Official and Nike Vintage? Include the product name, profit margin, and what business unit (Nike Official or Nike Vintage) sells the product.
*/


SELECT
		'Nike Official' AS "Nike Official",
		pr.product_name AS "Nike Official",
    (SUM(retail_price) - SUM(cost)) / SUM(retail_price) AS profit_margin
FROM products AS pr
WHERE product_name NOT LIKE('%Vintage%')
GROUP BY pr.product_name
UNION
SELECT 
		'Nike Vintage' AS "Nike Vintage",
		pr.product_name AS "Nike Vintage",
    (SUM(retail_price) - SUM(cost)) / SUM(retail_price) AS profit_margin
FROM products AS pr
WHERE product_name LIKE('%Vintage%')
GROUP BY pr.product_name
ORDER BY profit_margin DESC
LIMIT 10;
